name = "mandiboard"
main = ".output/server/index.mjs"
compatibility_date = "2025-05-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "mandiboard"
database_id = "5219e04f-92a5-49b4-85f1-b2fb3821433d"
preview_database_id = "mandiboard-local"
